theme: jekyll-theme-tactile
title: ionutsava674 home page
plugins:
  - jekyll-relative-links
relative-links:
  enabled: true
  collections: true
include:
  - index.md
  - portfolio.md- CoverLetter.md
